### PR TITLE
MNT: Added ppc64le support Re-rendered with conda-build 3.17.8, conda-smithy 3.3.4, and con…

### PR DESCRIPTION
**Pull request by ipoddar-ibm**
…da-forge-pinning 2019.05.11

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems to be missing the `wrapt` dependency.

**Comment by ipoddar-ibm** [comment]
I tried to manually run conda build . in the conda-forge-anvil-ppc64le docker image and that build went fine. It found and install wrapt, I see it is missing the wrapt package only for the arm architecture.
```
root@cit1000:~# docker run -it condaforge/linux-anvil-ppc64le
[conda@737e1c8e479e ~]$ conda activate base
(base) [conda@737e1c8e479e ~]$ cd /home/conda/
(base) [conda@737e1c8e479e ~]$ ls
(base) [conda@737e1c8e479e ~]$ git clone https://github.com/ipoddar-ibm/pygithub-feedstock.git
Cloning into 'pygithub-feedstock'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 340 (delta 45), reused 79 (delta 41), pack-reused 254
Receiving objects: 100% (340/340), 72.48 KiB | 1.81 MiB/s, done.
Resolving deltas: 100% (166/166), done.
(base) [conda@737e1c8e479e ~]$ cd pygithub-feedstock/
(base) [conda@737e1c8e479e pygithub-feedstock]$ conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for pygithub
INFO:conda_build.metadata:Attempting to finalize metadata for pygithub
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: ['pygithub-1.43.6-py37_0.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/pygithub_1557925290124/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h14c3975_1002  conda-forge
    ca-certificates: 2019.3.9-hecc5488_0  conda-forge
    certifi:         2019.3.9-py37_0      conda-forge
    libffi:          3.2.1-hb209c28_1006  conda-forge
    libgcc-ng:       8.2.0-h822a55f_1     defaults   
    libstdcxx-ng:    8.2.0-h822a55f_1     defaults   
    ncurses:         6.1-hf484d3e_1002    conda-forge
    openssl:         1.1.1b-h6eb9509_2    conda-forge
    pip:             19.1-py37_0          conda-forge
    python:          3.7.3-hd55099a_0     conda-forge
    readline:        7.0-hf8c457e_1001    conda-forge
    setuptools:      41.0.1-py37_0        conda-forge
    sqlite:          3.26.0-h67949de_1000 conda-forge
    tk:              8.6.9-h84994c4_1001  conda-forge
    wheel:           0.33.4-py37_0        conda-forge
    xz:              5.2.4-h14c3975_1001  conda-forge
    zlib:            1.2.11-h14c3975_1004 conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
Source cache directory is: /opt/conda/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: PyGithub-1.43.6_74cbc6a051.tar.gz
INFO:conda_build.source:Downloading source to cache: PyGithub-1.43.6_74cbc6a051.tar.gz
Downloading https://pypi.io/packages/source/P/PyGithub/PyGithub-1.43.6.tar.gz
INFO:conda_build.source:Downloading https://pypi.io/packages/source/P/PyGithub/PyGithub-1.43.6.tar.gz
Success
INFO:conda_build.source:Success
Extracting download
source tree in: /opt/conda/conda-bld/pygithub_1557925290124/work
export PREFIX=/opt/conda/conda-bld/pygithub_1557925290124/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export SRC_DIR=/opt/conda/conda-bld/pygithub_1557925290124/work
Processing $SRC_DIR
Building wheels for collected packages: PyGithub
  Building wheel for PyGithub (setup.py): started
  Building wheel for PyGithub (setup.py): finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-5oept7wt/wheels/78/35/98/05a60fe63f3f38ce91145bf1e2c0ba8cce4add3c8f6521084b
Successfully built PyGithub
Installing collected packages: PyGithub
Successfully installed PyGithub-1.43.6

Resource usage statistics from building pygithub:
   Process count: 3
   CPU time: Sys=0:00:01.0, User=0:00:35.7
   Memory: 98.2M
   Disk usage: 22.3K
   Time elapsed: 0:00:40.7

Packaging pygithub
INFO:conda_build.build:Packaging pygithub
Packaging pygithub-1.43.6-py37_0
INFO:conda_build.build:Packaging pygithub-1.43.6-py37_0
compiling .pyc files...
number of files: 916
Fixing permissions
Packaged license file.
Compressing to /tmp/tmp8bd_wfyd/pygithub-1.43.6-py37_0.tar.bz2
Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING:conda_build.build:Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
TEST START: /opt/conda/conda-bld/linux-ppc64le/pygithub-1.43.6-py37_0.tar.bz2
Adding in variants from /tmp/tmp4v5khjbg/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /tmp/tmp4v5khjbg/info/recipe/conda_build_config.yaml
Renaming work directory,  /opt/conda/conda-bld/pygithub_1557925290124/work  to  /opt/conda/conda-bld/pygithub_1557925290124/work_moved_pygithub-1.43.6-py37_0_linux-ppc64le
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/pygithub_1557925290124/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


The following NEW packages will be INSTALLED:

    asn1crypto:      0.24.0-py_1           conda-forge
    bzip2:           1.0.6-h14c3975_1002   conda-forge
    ca-certificates: 2019.3.9-hecc5488_0   conda-forge
    certifi:         2019.3.9-py37_0       conda-forge
    cffi:            1.12.3-py37hd553616_0 conda-forge
    chardet:         3.0.4-py37_1003       conda-forge
    cryptography:    2.6.1-py37h1905b30_0  conda-forge
    deprecated:      1.2.5-py_0            conda-forge
    idna:            2.8-py37_1000         conda-forge
    libffi:          3.2.1-hb209c28_1006   conda-forge
    libgcc-ng:       8.2.0-h822a55f_1      defaults   
    libstdcxx-ng:    8.2.0-h822a55f_1      defaults   
    ncurses:         6.1-hf484d3e_1002     conda-forge
    openssl:         1.1.1b-h6eb9509_2     conda-forge
    pip:             19.1-py37_0           conda-forge
    pycparser:       2.19-py_0             conda-forge
    pygithub:        1.43.6-py37_0         local      
    pyjwt:           1.7.1-py_0            conda-forge
    pyopenssl:       19.0.0-py37_0         conda-forge
    pysocks:         1.7.0-py37_0          conda-forge
    python:          3.7.3-hd55099a_0      conda-forge
    readline:        7.0-hf8c457e_1001     conda-forge
    requests:        2.21.0-py37_1000      conda-forge
    setuptools:      41.0.1-py37_0         conda-forge
    six:             1.12.0-py37_1000      conda-forge
    sqlite:          3.26.0-h67949de_1000  conda-forge
    tk:              8.6.9-h84994c4_1001   conda-forge
    urllib3:         1.24.3-py37_0         conda-forge
    wheel:           0.33.4-py37_0         conda-forge
    wrapt:           1.11.1-py37h7b6447c_0 defaults   
    xz:              5.2.4-h14c3975_1001   conda-forge
    zlib:            1.2.11-h14c3975_1004  conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
export PREFIX=/opt/conda/conda-bld/pygithub_1557925290124/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
export SRC_DIR=/opt/conda/conda-bld/pygithub_1557925290124/test_tmp
import: 'github'
import: 'github.tests'
import: 'github'
import: 'github.tests'

Resource usage statistics from testing pygithub:
   Process count: 1
   CPU time: Sys=0:00:00.0, User=0:00:00.0
   Memory: 4.1M
   Disk usage: 16B
   Time elapsed: 0:00:02.1

TEST END: /opt/conda/conda-bld/linux-ppc64le/pygithub-1.43.6-py37_0.tar.bz2
Renaming work directory,  /opt/conda/conda-bld/pygithub_1557925290124/work  to  /opt/conda/conda-bld/pygithub_1557925290124/work_moved_pygithub-1.43.6-py37_0_linux-ppc64le_main_build_loop
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /opt/conda/conda-bld/linux-ppc64le/pygithub-1.43.6-py37_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
####################################################################################
Resource usage summary:

Total time: 0:02:33.5
CPU usage: sys=0:00:01.0, user=0:00:35.7
Maximum memory usage observed: 98.2M
Total disk usage observed (not including envs): 22.3K
(base) [conda@737e1c8e479e pygithub-feedstock]$ 
```

**Comment by ipoddar-ibm** [comment]
I see now only the  ARM architecture builds are failing and there no logs. Can the jobs be restarted?

**Comment by ipoddar-ibm** [comment]
I made  a pull request  for the arm architecture build for wrapt: https://github.com/conda-forge/wrapt-feedstock/pull/12 . after that is merged, and the wrapt package is published, , i will rerun the checks for  this PR.

**Comment by ipoddar-ibm** [comment]
@jakirkham can this be merged now?

**Pull request merged**
